### PR TITLE
Support connection charset setting

### PR DESCRIPTION
**Pull request by estliberitas**
I had issue like https://github.com/Sannis/node-mysql-libmysqlclient/issues/131 and think it's good little feature - setting of charset for connection in Client. (or I see lots of "?" instead of localized symbols :))

### CODE REVIEW

**Comment by estliberitas** [comment]
ping @mgutz

**Comment by mgutz** [comment]
I'm on holiday, will merge when I get back.

**Comment by estliberitas** [comment]
ok

**Comment by mgutz** [comment]
Thanks!

**Comment by estliberitas** [comment]
Happy new year! Thank ya too :)

**Comment by estliberitas** [comment]
I was thinking of feature like:

``` javascript
mapper.client.configure(function(client) {
  client.setOptionSync(mysql.FLAG_1, val1);
  client.setOptionSync(mysql.FLAG_2, val2);
  /* ... */
});
```

It may be useful if one wants to control mysql connection (as example, sometimes I need to set `MYSQL_OPT_RECONNECT` flag). And with such thing we can avoid much code if we'd implement different client features. What do you think about such `configure(fn)` feature?

**Comment by mgutz** [comment]
Good idea! Added as issue #6. If you would like to submit pull request, I'll merge it in. I'm busy on my day job and I might not have free time until next week.

**Pull request merged**
